sudo: required
language: python
python:
  - "2.7"
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'

install:
  - sudo apt-get install sshpass
  - pip install docker-py
  - pip install jmespath
  - pip install ansible
  - ansible --version
  - ansible-galaxy install -r test/requirements.yml

script:
  - ansible-playbook -i test/inventory test/main.yml --syntax-check
  - ansible-playbook -i test/inventory test/main.yml -vvv
