# The package repository currently doesn't contain ARM64 packages,
# so we install packages stored in a github release instead.
#
# Revisit once https://github.com/grafana/carbon-relay-ng/pull/479
# is merged.
- include: install_from_github_release.yml
  when: install_from_github_release

- include: install_with_apt.yml
  when: not install_from_github_release

- name: Copy conf file
  template:
    src: carbon-relay-ng.conf
    dest: "{{ carbon_relay_ng_conf_dir }}/carbon-relay-ng.conf"
    mode: 0644
  notify: Restart carbon-relay-ng service

- name: Copy storage-schemas file
  template:
    src: storage-schemas.conf
    dest: "{{ carbon_relay_ng_conf_dir }}/storage-schemas.conf"
    mode: 0644
  notify: Restart carbon-relay-ng service

- name: Copy storage-aggregation file
  template:
    src: storage-aggregation.conf
    dest: "{{ carbon_relay_ng_conf_dir }}/storage-aggregation.conf"
    mode: 0644
  notify: Restart carbon-relay-ng service

- name: Create directory for pid file
  file:
    path: "{{ carbon_relay_ng_work_dir }}"
    state: directory
    owner: carbon-relay-ng
    group: carbon-relay-ng
    mode: 0755
  notify: Restart carbon-relay-ng service

- name: Copy carbon-relay-ng Supervisord config
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/carbon-relay-ng.conf
    mode: 0644
  notify: Reread Supervisor configuration
